version: "3.8"

services:
  web:
    build: .
    restart: on-failure
    container_name: web_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - db
  db:
    image: mysql
    restart: always
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=Bank
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - db_vol:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_vol: