version: "3.8"

services:
  web:
    build: .
    image: web:v1.0
    restart: on-failure
    container_name: web_app
    depends_on:
      - mysql_db
      - redis_db
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - mysql_db
    volumes:
      - .:/code
  mysql_db:
    image: mysql
    restart: always
    container_name: mysql_db
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  redis_db:
    image: bitnami/redis
    container_name: redis_db
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  mysql_data:
  redis_data: