version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-web
    image: web:v1.0
    restart: on-failure
    container_name: web_app
    depends_on:
      - mysqldb
      - redisdb
    ports:
      - "8081:8081"
    env_file:
      - .env
    links:
      - mysqldb
      - redisdb
    volumes:
      - .:/code
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: server:v1.0
    restart: on-failure
    container_name: server_app
    depends_on:
      - mysqldb
      - redisdb
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - mysqldb
      - redisdb
    volumes:
      - .:/code
  mysqldb:
    image: mysql
    restart: always
    container_name: mysqldb
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  redisdb:
    image: bitnami/redis
    container_name: redisdb
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  mysql_data:
  redis_data: