#Builder stage
FROM golang:1.15 AS BUILDER
WORKDIR /go/src/app
COPY . .
RUN make dependency
ENV CGO_ENABLED=0
RUN make buildWeb

#RUN_TIME stage
FROM alpine:latest AS RUN_TIME
COPY --from=BUILDER /go/src/app/.env ./
COPY --from=BUILDER /go/src/app/pkg/http/handler/web/templates ./templates
COPY --from=BUILDER /go/src/app/cmd/web/main ./
CMD ["./main"]